### ISSUE TITLE
Latex好像显示有点问题

### ISSUE THREAD

**Issue by NickPoon** [JayYip/deep-learning-nlp-notes#1]
图网络的那篇latex显示好像有点问题，如图

<img width="897" alt="image" src="https://user-images.githubusercontent.com/14728438/59350794-8bdd9c00-8d4f-11e9-984a-a977457b110e.png">

**Comment by JayYip** [comment]
所有LaTex都有问题... 目前还没有找到个方法方便地转

**Comment by JayYip** [comment]
没有完美解决方法... 安装README里面那个插件吧...

**Comment by NickPoon** [comment]
好的我试一下
